const swaggerAutogen = require('swagger-autogen')()
const path = require('path')
const outputFile = path.join(__dirname, '..',
    'swagger-output.json')
const endpointsFiles = [path.join(__dirname, 'routes', 'auth.js'), path.join(__dirname, 'routes', 'api.js')]
const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [{
        "name": "Server",
        "description": "Endpoints"
    }],
}
swaggerAutogen(outputFile, endpointsFiles, doc)